security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\Adherent:
            algorithm: bcrypt
    providers:
        in_database:
            entity:
                class: App\Entity\Adherent
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        api:
            pattern: ^/apiPlatform
            stateless: true
            anonymous: true
            json_login:
                check_path: /apiPlatform/login_check
                username_path: mail
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/apiPlatform/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apiPlatform$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apiPlatform, roles: IS_AUTHENTICATED_FULLY }
    
    role_hierarchy:
        ROLE_MANAGER: ROLE_ADHERENT
        ROLE_ADMIN: ROLE_MANAGER
